spring:
  application:
    name: TimeStock
  datasource:
    url: jdbc:mysql://localhost:3306/timestock?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

kis:
  token:
    url: https://openapi.koreainvestment.com:9443/oauth2/tokenP
  api:
    url: https://openapi.koreainvestment.com:9443/uapi/domestic-stock/v1/quotations/inquire-price
    app_key: PS4OD4jNPknZfi4of6WVg12tYqTmrHZ70LCv
    app_secret: rp2qlIHTSx2Qd8/aWx6sOlhFxNt1c5AMLXonbfxDUL05R3OYI0TiQXiEc3vAuFESN07F0V/X7WvFkiszA3F2rF3xYDCPlKgkDJM7oz2QoPdlg87WvWWF73qw63s5d0BRameYzPh788ZU4X/I61GKFWRI22qo4a57UPVWIsOqhXgEpVMQ8e4=
  oauth:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjIyYTc2MmExLTU3ZWItNDg2MS05YjRhLTM2MWIyMTcxMTgwOCIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTc0MDQ1ODUzMywiaWF0IjoxNzQwMzcyMTMzLCJqdGkiOiJQUzRPRDRqTlBrblpmaTRvZjZXVmcxMnRZcVRtckhaNzBMQ3YifQ.16wF33ZwPTOu87xatlDXKpgxocXMZ6vz_BZCGH1kmWV_S9b1SkG891MuqsT6onIIPZfHNRVlkcOdYi6tWaue7A
